name: Release
description: Releases packages in a monorepo
inputs:
  increments_by_scope:
    description: Increments gotten from detect-increment
    required: true
  new_packages:
    description: Packages which need to be published without a version bump
    required: true
runs:
  using: composite
  steps:
    - run: pnpm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: pnpm run build
      shell: bash
      working-directory: ${{ github.action_path }}
    - id: main
      run: pnpm start
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_INCREMENTS_BY_SCOPE: ${{ inputs.increments_by_scope }}
        INPUT_NEW_PACKAGES: ${{ inputs.new_packages }}