name: Check Change
on:
  pull_request:
    branches: [main, major, minor, patch]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ChocolateLoverRaj/npm-version/check@next