name: Check
on:
  pull_request:
    branches: [main]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Npm
        uses: ChocolateLoverRaj/npm-version/check@main
        with:
          same: true