name: Freeze
on:
  pull_request:
    branches: [main, major, minor, patch]
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Json
        uses: ChocolateLoverRaj/npm-version/freeze@main
        with:
          json: 'freeze.json'