name: Check Freeze
on:
  pull_request:
    branches: [main, major, minor, patch]
jobs:
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Json
        uses: ChocolateLoverRaj/npm-version/freeze@next
        with:
          options: 'freeze.json'