name: Release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup Pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.4
        run_install: true
    - id: get_increments
      name: Get Increment
      uses: ChocolateLoverRaj/detect-increment@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: get_new_packages
      name: Get New Packages
      uses: ./get-new-packages
      with:
        packages_glob: packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: ./release
      with:
        increments_by_scope: ${{ steps.get_increments.outputs.increments_by_scope }}
        new_packages: ${{ steps.get_new_packages.outputs.new_packages }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}