name: Release Preview
on:
  pull_request:
    branches: [main]
jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup Pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.4
    - id: get_increment
      name: Get Increment
      uses: ChocolateLoverRaj/detect-increment@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: get_packages_json
      name: Get Packages
      uses: ./list-to-json
      with:
        list: "$(ls packages)"
    - id: get_new_packages
      name: Get New Packages
      uses: ./get-new-packages
      with:
        packages_glob: packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: get_labels
      name: Get Labels
      run: |
        pnpm i
        pnpm build
        pnpm start
      working-directory: release-preview
      env:
        INPUT_PACKAGES: ${{ steps.get_packages_json.outputs.json }}
        INPUT_INCREMENTS: ${{ steps.get_increment.outputs.increments_by_scope }}
        INPUT_NEW_PACKAGES: ${{ steps.get_new_packages.outputs.new_packages }}
    - name: Update Pull Request Labels
      uses: ChocolateLoverRaj/label-manager@v1.0
      with:
        manage: ${{ steps.get_labels.outputs.manage }}
        set: ${{ steps.get_labels.outputs.set }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
