name: Release Preview
on:
  pull_request:
    branches: [main]
jobs:
  release-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Setup Pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.4
    - name: Release
      uses: ChocolateLoverRaj/pr-increment-preview@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
